.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dietbitcoin_qt test_dietbitcoin_qt
clean: FORCE
	$(MAKE) -C .. dietbitcoin_qt_clean test_dietbitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_dietbitcoin_qt_check
dietbitcoin-qt dietbitcoin-qt.exe: FORCE
	 $(MAKE) -C .. dietbitcoin_qt
